import { doc, setDoc, collection, serverTimestamp } from 'firebase/firestore';
import { db, auth } from '../../../utils/firebaseConfig';
import { createUserFolderStructure } from '../../files/services/fileService';
import { MEMBERSHIP_PLANS } from '../../membership/services/membershipService';
import { API_BASE_URL, fetchUserProfile } from '../../../utils/api';

export async function generateUserId() {
    console.warn('[userService] generateUserId is deprecated. ID is now generated by Backend (/users/init).');
    return null; 
}

export async function createUserProfile(userData, membershipPlan = 'free') {
    const userId = userData.uid;
    const userEmail = userData.email;
    const userName = userData.displayName || userEmail.split('@')[0];
    const uniqueUserId = await generateUserId();

    const now = new Date();
    const planDetails = MEMBERSHIP_PLANS[membershipPlan.toUpperCase()];
    const expiryDate = planDetails?.duration !== 'unlimited' ? new Date(now.getTime() + (30 * 24 * 60 * 60 * 1000)) : null;

  /* 
       SECURITY UPDATE: 
       Frontend does NOT write 'role'.
       Role is assigned by Backend via /users/init or Cloud Function.
    */
    const userProfile = {
        email: userEmail,
        displayName: userName,
        userId,
        // role: 'user', // <--- REMOVED: Managed by Backend
        accountCreatedAt: serverTimestamp(),
        accountCreatedDate: now.toISOString(),
        lastLoginAt: serverTimestamp(),
        /* 
           MEMBERSHIP UPDATE:
           Frontend does NOT write 'membership'.
           Default 'Free' plan is assigned by Backend via /users/init.
        */
        // membership: { ... }, // <--- REMOVED: Managed by Backend
        usage: {
            totalChats: 0, totalMessages: 0, totalFilesUploaded: 0,
            storageUsedMB: 0, monthlyQuotaUsed: 0, lastResetDate: now.toISOString()
        },
        settings: { notifications: true, emailUpdates: true, dataRetention: true }
    };
    if (uniqueUserId) {
        userProfile.uniqueUserId = uniqueUserId;
    }

    await setDoc(doc(db, 'users', userId), userProfile);
    await createUserFolderStructure(userId, userName);
    
    // Call Backend to initialize secure fields (Role)
    try {
        const token = await userData.getIdToken();
        // Assuming API_URL is accessible or we use a relative path if proxied. 
        // Using fetch to avoid circular deps if axios is not set up in this service file alone.
        // We need the API URL. Let's try to get it from env or hardcode fallback relative to where frontend expects.
        // Uses centralized API_BASE_URL from utils/api.
        
        await fetch(`${API_BASE_URL}/users/init`, {
            method: 'POST',
            headers: {
                'Authorization': `Bearer ${token}`,
                'Content-Type': 'application/json'
            }
        });
        console.log('[userService] Backend initialized user role.');
    } catch (e) {
        console.error('[userService] Failed to call backend init:', e);
        // Does not block flow, but warns. Backend will eventually catch it on next login if we check there too.
    }

    return userProfile;
}

export async function updateUserUsage(userId, updates) {
    console.warn('[userService] updateUserUsage is deprecated. Usage is now tracked on the backend.');
    // Function disabled for security.
}

export async function updateUserLastLogin(userId) {
    // DEPRECATED: Backend /users/init handles lastLoginAt now.
    console.warn('[userService] updateUserLastLogin is deprecated. Backend handles this via /users/init.');
    // No-op for security
}

export async function assignUserIdToExistingUser(userId, userData) {
    // DEPRECATED: Backend /users/init generates and assigns uniqueUserId.
    console.warn('[userService] assignUserIdToExistingUser is deprecated. Backend generates IDs.');
    // Return existing ID if available, otherwise null (backend will assign)
    return userData?.uniqueUserId || null;
}

export async function ensureUserHasId(userId) {
    try {
        const payload = await fetchUserProfile();
        const userData = payload?.user;
        if (!userData) {
            console.warn('[ensureUserHasId] User profile not found');
            return null;
        }

        if (userData.uniqueUserId) {
            return userData.uniqueUserId;
        }

        console.log('[ensureUserHasId] uniqueUserId missing. Calling Backend /users/init...');
        
        try {
            const { auth } = await import('../../../utils/firebaseConfig');
            const token = await auth.currentUser?.getIdToken(true);
            
            if (token) {
                const response = await fetch(`${API_BASE_URL}/users/init`, {
                    method: 'POST',
                    headers: {
                        'Authorization': `Bearer ${token}`,
                        'Content-Type': 'application/json'
                    }
                });
                
                if (response.ok) {
                    const initPayload = await response.json().catch(() => null);
                    if (initPayload?.uniqueUserId) {
                        console.log('[ensureUserHasId] Got uniqueUserId from init:', initPayload.uniqueUserId);
                        return initPayload.uniqueUserId;
                    }
                    console.log('[ensureUserHasId] Backend init successful, re-fetching user...');
                    const refreshed = await fetchUserProfile();
                    const newId = refreshed?.user?.uniqueUserId || null;
                    if (newId) {
                        console.log('[ensureUserHasId] Got uniqueUserId from refresh:', newId);
                    }
                    return newId;
                } else {
                    console.error('[ensureUserHasId] Backend init failed:', response.status);
                }
            } else {
                console.warn('[ensureUserHasId] No auth token available');
            }
        } catch (backendError) {
            console.error('[ensureUserHasId] Backend call error:', backendError);
        }
        
        return null;
    } catch (error) {
        console.error('[ensureUserHasId] Error:', error);
        return null;
    }
}

async function getRoleFromClaims(userId) {
    const current = auth.currentUser;
    if (!current || current.uid !== userId) return '';
    const tokenResult = await current.getIdTokenResult(true);
    const claims = tokenResult?.claims || {};
    const role = claims.role || (claims.superadmin ? 'superadmin' : claims.admin ? 'admin' : '');
    return role === 'super_admin' ? 'superadmin' : (role || '');
}

export async function getUserRole(userId) {
    try {
        const claimRole = await getRoleFromClaims(userId);
        if (claimRole) {
            return claimRole;
        }
        const userData = await getUserData(userId);
        const rawRole = userData?.role;

        if (!rawRole) {
            throw new Error('Role missing for user');
        }

        const normalizedRole = rawRole === 'super_admin' ? 'superadmin' : rawRole;
        return normalizedRole;
    } catch (error) {
        console.error('[getUserRole] Failed to resolve role:', error);
        throw error;
    }
}

export async function getUserData(userId) {
    const payload = await fetchUserProfile();
    if (!payload?.user) {
        throw new Error('User profile not found');
    }
    return payload.user;
}




